version: '3'
services:
  app:
    build: ./docker/php
    container_name: skillup_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: skillup_nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/mvc-shop.com.conf:/etc/nginx/conf.d/mvc-shop.com.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/mvc-shop-hw.com.conf:/etc/nginx/conf.d/mvc-shop-hw.com.conf
      - ./docker/nginx/mvc-shop-2020-11-30.com.conf:/etc/nginx/conf.d/mvc-shop-2020-11-30.com.conf
      - ./docker/nginx/projekt.com.conf:/etc/nginx/conf.d/projekt.com.conf
      - ./docker/nginx/yiiproject.com.conf:/etc/nginx/conf.d/yiiproject.com.conf
    depends_on:
      - app
  db:
    image: mysql:8.0.22
    ports:
      - 3300:3306
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: artur_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: artur_shop
      MYSQL_USER: artur_base
      MYSQL_PASSWORD: artur_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1